name: Re-tag image

on:
  workflow_dispatch:
    inputs:
      new-tag:
        type: string
        required: true
        default: "new-tag"
      image:
        type: string
        required: true
        default: "ghcr.io/borislavr/opensearch"
      old-tag:
        type: string
        required: true
        default: "2.19.3"
permissions:
  contents: read
  packages: write

jobs:
  re-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef  # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Re-tag image
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo snap install regclient 
          echo "${token}" | regctl registry login ghcr.io -u "${GITHUB_REPOSITORY_OWNER}" --pass-stdin
          regctl image copy --verbosity info ${{ inputs.image }}:${{ inputs.old-tag }} ${{ inputs.image }}:${{ inputs.new-tag }}
